import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { SoftwareDiversityCardGeneratedModule, SoftwareDiversityCardGeneratedSharedModule } from './generated/module.js';
import { SoftwareDiversityCardValidator, registerValidationChecks } from './swdc-dsl-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SoftwareDiversityCardAddedServices = {
    validation: {
        SoftwareDiversityCardValidator: SoftwareDiversityCardValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SoftwareDiversityCardServices = LangiumServices & SoftwareDiversityCardAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SoftwareDiversityCardModule: Module<SoftwareDiversityCardServices, PartialLangiumServices & SoftwareDiversityCardAddedServices> = {
    validation: {
        SoftwareDiversityCardValidator: () => new SoftwareDiversityCardValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSoftwareDiversityCardServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SoftwareDiversityCard: SoftwareDiversityCardServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SoftwareDiversityCardGeneratedSharedModule
    );
    const SoftwareDiversityCard = inject(
        createDefaultModule({ shared }),
        SoftwareDiversityCardGeneratedModule,
        SoftwareDiversityCardModule
    );
    shared.ServiceRegistry.register(SoftwareDiversityCard);
    registerValidationChecks(SoftwareDiversityCard);
    return { shared, SoftwareDiversityCard };
}
